ADD: Sponsors section
gdsc-nits-org/oikyotaan-2024 pull request #4
Opened 2024-04-04 14:31 UTC by aryanh0911

initial commit for the Sponsors section in the home page.

2024-04-04 16:15 UTC, bj-jiwrajka requested changes

2024-04-04 16:15 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorsStyle.css
> +    margin-left: auto; */
if the code is not required, remove it

2024-04-04 16:15 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorCards/SponsorCardsStyles.css
> +  width: 280px;
avoid using px, convert it to relative units such as rem/em

2024-04-04 16:15 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorCards/SponsorCards.jsx
> +import React from 'react'
import of react is not required after react version 17

2024-04-04 18:41 UTC, bj-jiwrajka requested changes

2024-04-04 18:41 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorHeading/SponsorHeading.jsx
> +            <p className='title'>Sponsors</p>
font doesn't match with the design and the letters are uppercase in the design

2024-04-04 19:52 UTC, bj-jiwrajka requested changes

2024-04-04 19:52 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorCards/SponsorCards.jsx
> +
avoid using functional component

2024-04-04 19:52 UTC, bj-jiwrajka commented on src/Components/Sponsors/SponsorCards/SponsorCardsStyles.css
> +  grid-template-columns: auto auto auto; */
remove unnecessary comments

2024-04-04 19:54 UTC, bj-jiwrajka commented
Some more changes:

- Use module css (take reference from rest of the pages)
- Card size is too big, make it small

2024-04-05 10:22 UTC, Hrishita-Paul requested changes
1)Reduce the shadowing effect on the images
2)Add the images of the flowers in the background
3)Check the mobile view on the figma link and make changes

2024-04-05 19:37 UTC, closed without merging